export const Anime = [
  'Fullmetal Alchemist: Brotherhood',
  'Gintama°',
  'Steins;Gate',
  'Shingeki no Kyojin Season 3 Part 2',
  'Shingeki no Kyojin: The Final Season Part 2',
  'Gintama°;',
  'Gintama: The Final',
  'Hunter x Hunter (2011)',
  'Fruits Basket: The Final',
  'Gintama°;: Enchousen',
  'Ginga Eiyuu Densetsu',
  'Gintama.',
  '3-gatsu no Lion 2nd Season',
  'Koe no Katachi',
  'Violet Evergarden Movie',
  'Gintama',
  'Clannad: After Story',
  'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare',
  'Code Geass: Hangyaku no Lelouch R2',
  'Kimetsu no Yaiba: Yuukaku-hen',
  'Owarimonogatari 2nd Season',
  'Gintama.: Shirogane no Tamashii-hen - Kouhan-sen',
  'Kimi no Na wa.',
  'Shingeki no Kyojin: The Final Season',
  'Monster',
  'Gintama.: Shirogane no Tamashii-hen',
  'Kizumonogatari III: Reiketsu-hen',
  'Mob Psycho 100 II',
  'Shiguang Dailiren',
  'Haikyuu!!: Karasuno Koukou vs. Shiratorizawa Gakuen Koukou',
  'Sen to Chihiro no Kamikakushi',
  'Monogatari Series: Second Season',
  'Kingdom 3rd Season',
  'Cowboy Bebop',
  'Mushoku Tensei: Isekai Ittara Honki Dasu Part 2',
  'Odd Taxi',
  'Ousama Ranking',
  'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen',
  'Mushishi Zoku Shou 2nd Season',
  'Hajime no Ippo',
  'Vinland Saga',
  'Fate/stay night Movie: Heaven°;s Feel - III. Spring Song',
  '86 Part 2',
  'Ashita no Joe 2',
  'Mo Dao Zu Shi: Wanjie Pian',
  'Mushishi Zoku Shou',
  'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen',
  'Code Geass: Hangyaku no Lelouch',
  'Jujutsu Kaisen (TV)',
  'Great Teacher Onizuka',
  'Kimetsu no Yaiba Movie: Mugen Ressha-hen',
  'Made in Abyss',
  'Made in Abyss Movie 3: Fukaki Tamashii no Reimei',
  'Mononoke Hime',
  'Mushishi',
  'Shigatsu wa Kimi no Uso',
  'Violet Evergarden',
  'Hajime no Ippo: New Challenger',
  'Howl no Ugoku Shiro',
  'Evangelion: 3.0+1.0 Thrice Upon a Time',
  'Haikyuu!! Second Season',
  'Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen',
  'Natsume Yuujinchou Shi',
  'Tengen Toppa Gurren Lagann',
  'Natsume Yuujinchou Roku',
  'One Piece',
  'Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai',
  'Shingeki no Kyojin Season 3',
  'Death Note',
  'Ping Pong the Animation',
  'Suzumiya Haruhi no Shoushitsu',
  'Mushishi Zoku Shou: Suzu no Shizuku',
  'Ookami Kodomo no Ame to Yuki',
  'Shouwa Genroku Rakugo Shinjuu',
  'Kizumonogatari II: Nekketsu-hen',
  'Hajime no Ippo: Rising',
  'JoJo no Kimyou na Bouken Part 5: Ougon no Kaze',
  'Natsume Yuujinchou Go',
  'Natsume Yuujinchou San',
  'Shoujo☆Kageki Revue Starlight Movie',
  'Yojouhan Shinwa Taikei',
  'Tengen Toppa Gurren Lagann Movie 2: Lagann-hen',
  'Fate/Zero 2nd Season',
  'Fruits Basket 2nd Season',
  'Kimi no Suizou wo Tabetai',
  'Kimetsu no Yaiba',
  'Bakuman. 3rd Season',
  'Jujutsu Kaisen 0 Movie',
  'Mushishi: Hihamukage',
  'Neon Genesis Evangelion: The End of Evangelion',
  'Yakusoku no Neverland',
  'Zoku Natsume Yuujinchou',
  'Sora yori mo Tooi Basho',
  'Yuru Camp△ Season 2',
  'Haikyuu!! To the Top 2nd Season',
  'Kara no Kyoukai 5: Mujun Rasen',
  'Karakai Jouzu no Takagi-san 3',
  'Fate/stay night Movie: Heaven&#039;s Feel - II. Lost Butterfly',
  'Gintama.: Porori-hen',
  'Kenpuu Denki Berserk',
];

export const Music = [
  'Cool For The Summer',
  'Heat Waves',
  'Bam Bam',
  'Enemy',
  'MIDDLE OF THE NIGHT',
  'Cold Heart',
  'Pepas',
  'Wait A Minute!',
  'abcdefu',
  'Tom’s Diner',
  'Where Did You Go?',
  'In The Dark',
  'Another Love',
  'Big Energy',
  'Clap Your Hands',
  'The Motto (Mixed)',
  'Yo Voy',
  'Where Are You Now',
  'Do It to It',
  'Mi Gata',
  'Say It Right',
  'Won’t Forget You',
  'Drip or Drown Remix',
  'Ainsi Bas La Vida',
  'Go Down Deh [Mixed]',
  'Finesse',
  'I’m Alone',
  'Peru',
  'TO THE MOON',
  'Infinity',
  'Fingers Crossed',
  'Abo Mvelo',
  'Calm Down',
  'Something In The Way',
  'Money Rain (Phonk Remix)',
  'Ameno Amapiano Remix',
  'Get Lucky',
  'Stay',
  'Dancing On My Own',
  'Rocking A Cardigan in Atlanta',
  'Unstoppable',
  'INDUSTRY BABY (Mixed)',
  'MAMIII',
  'Una Noche en Medellín',
  'THATS WHAT I WANT',
  'Mujeriego',
  'Fayahh',
  'Gangsteritus',
  'Shivers',
  'El Incomprendido',
  'Mount Everest',
  'Light Switch',
  'Dancin (Krono Remix)',
  'Just A Cloud Away',
  'Frozen',
  'Always',
  'Oh My God',
  'Monëy so big',
  'Ghost',
  'Bones',
  'Move Your Body (Mixed)',
  'Thinking With My D**k',
  'Asa - Xosa',
  'Bad Habits',
  'Emiliana',
  'Gangsta’s Paradise',
  'LA FAMA',
  'love nwantiti [Remix]',
  'Woman',
  'she’s all i wanna be',
  'Trompeta',
  'Sweetest Pie',
  'Anyone For You',
  'Soy El Unico',
  'N’y pense plus',
  'Sign of the Times (Stripped)',
  'Nobody Like U',
  'Boyfriend',
  'Down Under',
  'Streets',
  'Easy On Me',
  'Ginseng Strip 2002',
  'Essence [Mixed]',
  'No Wahala',
  'Gbona',
  'Overpass Graffiti',
  'Sungba',
  'When I’m Gone',
  'Chale',
  'Starlight',
  'Beggin’',
  'Save Your Tears',
  'Odg',
  'Mon Amour (Remix)',
  'Your Love',
  'Old Town Road (Remix)',
  'Suavemente',
  'Gangster',
  'Wrecking Ball',
  'All in one',
  'Blinding Lights',
  'The Jungle',
  'Hymn For The Weekend',
  'Toxic',
  'UP',
  'Somebody That I Used To Know',
  'Let Her Go',
  'Friendships (Lost My Love)',
  'Freaky Deaky',
  'Substance',
  'Love Tonight',
  'Sacrifice',
  'Doin’ Time',
  'Hrs and Hrs',
  'Propaganda',
  'Suave',
  'I Am Woman',
  'Hallucination',
  'Moth to a Flame (Mixed)',
  'Lonely',
  'GHOST TOWN',
  'Fuera del mercado',
  'In Your Arms (For An Angel)',
  'Softcore',
  'Dancing Feet',
  'Careless Whisper',
  'Numb',
  'Envolver',
  'My Universe',
  'Stereo Love',
  'Unforgettable',
  'Around The World',
  'Over',
  'Come & Go',
  'No Lie',
  'COMPLETE MESS',
  'Without Me',
  'Let Somebody Go',
  'Into Your Arms',
  'Valerie (Version Revisited)',
  'Notion',
  'Numb Little Bug',
  'Tacones Rojos',
  'Let My Love Open The Door',
  'Locked Out Of Heaven',
  'Danza Kuduro',
  'Super Gremlin',
  'Black Summer',
  'Thunder',
  'House Of The Rising Sun',
  'this is what falling in love feels like',
  'Over',
  'edamame',
  'RENCONTRE',
  'Perfect',
  'All Time Low',
  'Desesperados',
  'L’enfer',
  'Christmas Tree',
  'Don’t Forget My Love',
  'Arcade',
  'I Love You So',
  'Belly Dancer',
  'Sahara',
  'Earned It',
  'Someone You Loved',
  'Before I Ever Met You (Sohn Remix)',
  'Come A Little Closer',
  'Taca a Xereca pra Mim',
  'Sexyback',
  'Swim',
  'After Dark',
  'МАЛИНОВАЯ ЛАДА',
  'One Dance',
  'Remedy',
  'Nothing Breaks Like A Heart',
  'City of Gods',
  'Runaway',
  'Levitating',
  'Safe And Sound',
  'Revenge',
  'Dance Monkey',
  'Dégaine',
  'Attention',
  'Sad Girlz Luv Money Remix',
  'All The Things She Said',
  'Everyday Normal Guy 2',
  'Leave Before You Love Me',
  'Demasiadas Mujeres',
  'Captain (whistle)',
  'Loading',
  'Yeah!',
  `03' Bonnie & Clyde`,
  'NBAYOUNGBOAT',
  'Sigue',
  'Tourner Dans Le Vide',
  'Funkytown',
  'Притяжение (Official remix)',
  'Heat Waves (Slowed)',
  'Need To Know',
];
