// Current Length 100
export const Anime = [
  'A Silent Voice',
  'Akira',
  'Angel Beats',
  'Anohana',
  'Attack on Titan',
  'Bleach',
  'Clannad',
  'Code Geass',
  'Cowboy Bebop',
  'Death Note',
  'Demon Slayer',
  'Detective Conan',
  'Devilman Crybaby',
  'Dragon Ball',
  'Ecchi',
  'Elfen Lied',
  'Fairy Tail',
  'Fate',
  'Fate Stay Night',
  'Fate/Apocrypha',
  'Fate/Zero',
  'Fullmetal Alchemist',
  'Ghost in the Shell',
  'Gintama',
  'Haikyuu!!',
  'Hajime No Ippo',
  'Hunter x Hunter',
  'Inuyasha',
  'JoJo’s Bizarre Adventure',
  'Jujutsu Kaisen',
  'K-On',
  'KonoSuba',
  'Love Live!',
  'Made in Abyss',
  'Mob Psycho 100',
  'Monogatari Series',
  'Monster',
  'Mushishi',
  'My Hero Academia',
  'Naruto',
  'Neon Genesis Evangelion',
  'One Piece',
  'One-Punch Man',
  'OreGairu',
  'Parasyte',
  'Pokémon',
  'Re:Zero',
  'Spirited Away',
  'Steins;Gate',
  'The Melancholy of Haruhi Suzumiya',
  'Tokyo Ghoul',
  'Tokyo Revengers',
  'Violet Evergarden',
  'Weathering With You',
  'Your Name',
];

// Current Length 436
export const Music = [
  "03' Bonnie & Clyde",
  'Abo Mvelo',
  'Addicted',
  'Adorn',
  'After Dark',
  'Ainsi Bas La Vida',
  'Airplanes',
  'Alejandro',
  'All The Things She Said',
  'All Time Low',
  'All in one',
  'Always',
  'Amnesia',
  'Anaconda',
  'Animal',
  'Animals',
  'Another Love',
  'Antidote',
  'Anyone For You',
  'Apologize',
  'Applause',
  'Arcade',
  'Asa - Xosa',
  'Attention',
  'Ayo',
  'Baby',
  'Backseat',
  'Bad',
  'Bad Habits',
  'Bailando',
  'Bam Bam',
  'Bartender',
  'Battlefield',
  'Beachin’',
  'Beautiful',
  'Bed',
  'Beggin’',
  'Believer',
  'Belly Dancer',
  'Berzerk',
  'Better',
  'Big Energy',
  'Billionaire',
  'Birthday',
  'Black Summer',
  'Blessings',
  'Blinding Lights',
  'Blow',
  'Bones',
  'Both',
  'Boyfriend',
  'Brave',
  'Breathin’',
  'Broccoli',
  'Brokenhearted',
  'Bubbly',
  'Budapest',
  'Bugatti',
  'Burn',
  'Buttons',
  'COMPLETE MESS',
  'Calm Down',
  'Captain (whistle)',
  'Cardigan',
  'Careless Whisper',
  'Caroline',
  'Centuries',
  'Chains',
  'Chale',
  'Chandelier',
  'Changes',
  'Christmas Tree',
  'Circles',
  'Circus',
  'City of Gods',
  'Clap Your Hands',
  'Clarity',
  'Classic',
  'Climax',
  'Close',
  'Closer',
  'Clout',
  'Clumsy',
  'CoCo',
  'Cold',
  'Cold Heart',
  'Come & Go',
  'Come A Little Closer',
  'Congratulations',
  'Controlla',
  'Crazy',
  'Cruise',
  'Crush',
  'Cyclone',
  'Damaged',
  'Dance Monkey',
  'Dancing Feet',
  'Dancing On My Own',
  'Dangerous',
  'Danza Kuduro',
  'Daylight',
  'Delicate',
  'Demasiadas Mujeres',
  'Demons',
  'Desesperados',
  'Despacito',
  'Diamonds',
  'Dirt',
  'Disturbia',
  'Diva',
  'Do It to It',
  'Doin’ Time',
  'Domino',
  'Don’t',
  'Down',
  'Down Under',
  'Downtown',
  'Drowning',
  'Dueces',
  'Dura',
  'Dynamite',
  'Dégaine',
  'Earned It',
  'Eastside',
  'Easy On Me',
  'El Incomprendido',
  'Emiliana',
  'Enemy',
  'Envolver',
  'Essence',
  'Everyday Normal Guy 2',
  'Exchange',
  'Fancy',
  'Fayahh',
  'Feels',
  'Fefe',
  'Fergalicious',
  'Finesse',
  'Fingers Crossed',
  'Fireflies',
  'Firework',
  'Forever',
  'Franchise',
  'Freaky Deaky',
  'Friends',
  'Friendships',
  'Frozen',
  'Fuera del mercado',
  'Funkytown',
  'GHOST TOWN',
  'Gangster',
  'Gangsteritus',
  'Gbona',
  'Ghost',
  'Girlfriend',
  'Glamorous',
  'Gold',
  'Goodbye',
  'Goodbyes',
  'Goosebumps',
  'Grenade',
  'Grillz',
  'Gummo',
  'Hallucination',
  'Halo',
  'Happier',
  'Happy',
  'Hard',
  'Havana',
  'Headlines',
  'Heartless',
  'Heat Waves',
  'Heathens',
  'Heaven',
  'Hello',
  'Here',
  'Home',
  'Hrs and Hrs',
  'Humble',
  'Hurricane',
  'Hypnotized',
  'I Am Woman',
  'I Love You So',
  'Impossible',
  'In The Dark',
  'In Your Arms',
  'Independent',
  'Infinity',
  'Into Your Arms',
  'Irreplacable',
  'Issues',
  'I’m Alone',
  'Jealous',
  'Jumpman',
  'LA FAMA',
  'Latch',
  'Leave Before You Love Me',
  'Leavin’',
  'Lemon',
  'Let Her Go',
  'Let Somebody Go',
  'Levitating',
  'Lifestyle',
  'Light Switch',
  'Lighters',
  'Lights',
  'Loading',
  'Location',
  'Lollipop',
  'Lonely',
  'Love',
  'Love Tonight',
  'Low',
  'Loyal',
  'Loyalty',
  'Luv',
  'L’enfer',
  'MAMIII',
  'Magic',
  'Magnolia',
  'Malibu',
  'Maps',
  'Me!',
  'Mercy',
  'Mi Gata',
  'Mia',
  'Middle',
  'Mine',
  'Mirrors',
  'Misery',
  'Mon Amour (Remix)',
  'Money',
  'Money Rain',
  'Monëy so big',
  'Mood',
  'Moonlight',
  'More',
  'Motivation',
  'MotorSport',
  'Mount Everest',
  'Mujeriego',
  'My Universe',
  'NBAYOUNGBOAT',
  'Natural',
  'Naturally',
  'Need To Know',
  'No',
  'No Lie',
  'No Wahala',
  'Nobody Like U',
  'Nonstop',
  'Notion',
  'Numb',
  'Numb Little Bug',
  'N’y pense plus',
  'Odg',
  'Oh My God',
  'Old Town Road',
  'One Dance',
  'Only',
  'Oui',
  'Over',
  'Overpass Graffiti',
  'Panda',
  'Panini',
  'Paparazzi',
  'Paradise',
  'Paralyzer',
  'Paris',
  'Partition',
  'Passionfruit',
  'Payphone',
  'Pepas',
  'Perfect',
  'Peru',
  'Photograph',
  'Pillowtalk',
  'Pompeii',
  'Pontoon',
  'Positions',
  'Powerglide',
  'Praying',
  'Problem',
  'Promiscuous',
  'Promise',
  'Propaganda',
  'Psycho',
  'RENCONTRE',
  'Radioactive',
  'Ransom',
  'Realize',
  'Redbone',
  'Rehab',
  'Remedy',
  'Renegades',
  'Replay',
  'Revenge',
  'Ride',
  'Ridin’',
  'Riptide',
  'Roar',
  'Robbery',
  'Rockabye',
  'Rocketeer',
  'Rocking A Cardigan in Atlanta',
  'Rockstar',
  'Rolex',
  'Roses',
  'Royals',
  'Rude',
  'Rumor',
  'Runaway',
  'Sacrifice',
  'Sad Girlz Luv Money',
  'Sad!',
  'Safe And Sound',
  'Sahara',
  'Sail',
  'Savage',
  'Save Your Tears',
  'Say',
  'Say It Right',
  'Scream',
  'Secrets',
  'Senorita',
  'Sexyback',
  'Shallow',
  'Shivers',
  'Shower',
  'Sigue',
  'Simple',
  'Sing',
  'Slide',
  'Slippery',
  'Smile',
  'Sober',
  'Softcore',
  'Somebody',
  'Someone You Loved',
  'Sorry',
  'Soy El Unico',
  'Speechless',
  'Springteen',
  'Starboy',
  'Starlight',
  'Starships',
  'Starving',
  'Stay',
  'Stereo Love',
  'Stitches',
  'Streets',
  'Stronger',
  'Studio',
  'Style',
  'Suave',
  'Suavemente',
  'Substance',
  'Sucker',
  'Suffocate',
  'Sugar',
  'Suge',
  'Summer',
  'Sunflower',
  'Sungba',
  'Super Gremlin',
  'Superstar',
  'Swalia',
  'Sweetest Pie',
  'Swervin',
  'Swim',
  'Swnag',
  'TO THE MOON',
  'Tacones Rojos',
  'Talk',
  'Taste',
  'Tattoo',
  'Team',
  'Telephone',
  'Temperature',
  'Tequila',
  'The Jungle',
  'Then',
  'Thinking With My D**k',
  'Thotiana',
  'Thunder',
  'Timber',
  'Titanium',
  'Tourner Dans Le Vide',
  'Toxic',
  'Trampoline',
  'Treasure',
  'Trip',
  'Trollz',
  'Trompeta',
  'Trumpets',
  'Try',
  'Tuesday',
  'UP',
  'Umbrella',
  'Unforgettable',
  'Unsteady',
  'Unstoppable',
  'Untouched',
  'Unwritten',
  'Valerie',
  'WAP',
  'Wait',
  'Wait A Minute!',
  'Wanted',
  'Waves',
  'When I’m Gone',
  'Where Are You Now',
  'Whistle',
  'Wicked',
  'Wiggle',
  'Without Me',
  'Wolves',
  'Woman',
  'Womanizer',
  'Won’t Forget You',
  'Work',
  'Wow',
  'Wrecking Ball',
  'X',
  'Yeah!',
  'Yo Voy',
  'You',
  'Youngblood',
  'Your Love',
  'Zeze',
  'abcdefu',
  'edamame',
  'love nwantiti',
  'she’s all i wanna be',
  'МАЛИНОВАЯ ЛАДА',
  'Притяжение',
];
